import React from 'react';
import { View, Text, StyleSheet, StatusBar, Platform, TouchableOpacity, TextInput, ScrollView, useWindowDimensions } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import BottomNavBar from '../components/BottomNavBar';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { Ionicons, MaterialIcons } from '@expo/vector-icons';

type RootStackParamList = {
  GetStarted: undefined;
  SignIn: undefined;
  CreateAccount: undefined;
  SchoolUpdates: undefined;
  AIChat: undefined;
  UserSettings: undefined;
};

const SUGGESTIONS = [
  'How do I apply for a scholarship?',
  'Where is the library located?',
  'What\'s the enrollment schedule?',
  'How do I access my student portal?',
  'How do I reset my password?'
];

const AIChat = () => {
  const insets = useSafeAreaInsets();
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>();
  const { width } = useWindowDimensions();
  const isWide = width > 600;

  return (
    <View style={[styles.container, {
      paddingTop: insets.top,
      paddingBottom: insets.bottom,
      paddingLeft: insets.left,
      paddingRight: insets.right,
    }]}
    >
      <StatusBar
        backgroundColor="transparent"
        barStyle="dark-content"
        translucent={true}
      />
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.headerIcon}>
          <Ionicons name="close" size={28} color="#fff" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>DOrSU AI</Text>
        <TouchableOpacity style={styles.headerIcon}>
          <Ionicons name="information-circle-outline" size={26} color="#fff" />
        </TouchableOpacity>
      </View>
      {/* Content */}
      <ScrollView contentContainerStyle={[styles.scrollContent, { flex: 1, justifyContent: 'center' }]} keyboardShouldPersistTaps="handled">
        <View style={styles.centerIconContainer}>
          <MaterialIcons name="close" size={80} color="#AAA" style={styles.centerIcon} />
        </View>
        <Text style={styles.askTitle}>Ask DOrSU AI anything</Text>
        <Text style={styles.disclaimer}>Messages are generated by AI. Some may be inaccurate or inappropriate.</Text>
      </ScrollView>

      <View style={styles.suggestionsContainer}>
        <View style={[styles.suggestionRow, isWide && { maxWidth: 600 }]}>
          <TouchableOpacity style={[styles.suggestionBtn, isWide && styles.suggestionBtnWide]}><Text style={styles.suggestionText}>{SUGGESTIONS[0]}</Text></TouchableOpacity>
          <TouchableOpacity style={[styles.suggestionBtn, isWide && styles.suggestionBtnWide]}><Text style={styles.suggestionText}>{SUGGESTIONS[1]}</Text></TouchableOpacity>
        </View>
        <View style={[styles.suggestionRow, isWide && { maxWidth: 600 }]}>
          <TouchableOpacity style={[styles.suggestionBtn, isWide && styles.suggestionBtnWide]}><Text style={styles.suggestionText}>{SUGGESTIONS[2]}</Text></TouchableOpacity>
          <TouchableOpacity style={[styles.suggestionBtn, isWide && styles.suggestionBtnWide]}><Text style={styles.suggestionText}>{SUGGESTIONS[3]}</Text></TouchableOpacity>
        </View>
        <View style={[styles.suggestionRow, styles.suggestionRowSingle, isWide && { maxWidth: 600 }]}>
          <TouchableOpacity style={[styles.suggestionBtn, isWide && styles.suggestionBtnWide]}><Text style={styles.suggestionText}>{SUGGESTIONS[4]}</Text></TouchableOpacity>
        </View>
      </View>

      {/* Message Input Bar */}
      <View style={styles.inputBar}>
        <TextInput
          style={styles.input}
          placeholder="Message"
          placeholderTextColor="#888"
        />
        <TouchableOpacity style={styles.sendBtn}>
          <Ionicons name="arrow-forward" size={24} color="#222" />
        </TouchableOpacity>
      </View>
      <BottomNavBar
        activeTab="chat"
        onHomePress={() => navigation.navigate('SchoolUpdates')}
        onChatPress={() => navigation.navigate('AIChat')}
        onSettingsPress={() => navigation.navigate('UserSettings')}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F2F0E9',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingTop: 4,
    paddingBottom: 8,
    backgroundColor: '#333333',
    borderBottomWidth: 1,
    borderBottomColor: '#DDD',
  },
  headerIcon: {
    padding: 4,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
  },
  scrollContent: {
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  centerIconContainer: {
    marginTop: 16,
    marginBottom: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  centerIcon: {
    opacity: 0.2,
  },
  askTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#222',
    textAlign: 'center',
    marginBottom: 4,
  },
  disclaimer: {
    fontSize: 12,
    color: '#888',
    textAlign: 'center',
    marginBottom: 16,
  },
  suggestionsContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 8,
    paddingHorizontal: 8,
  },
  suggestionRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 8,
    width: '100%',
    alignSelf: 'center',
  },
  suggestionRowSingle: {
    justifyContent: 'center',
  },
  suggestionBtn: {
    backgroundColor: '#fff',
    borderColor: '#AAA',
    borderWidth: 1,
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 14,
    marginHorizontal: 4,
    alignItems: 'center',
    marginBottom: 4,
    minWidth: 0,
    maxWidth: '48%',
  },
  suggestionBtnWide: {
    paddingHorizontal: 32,
    marginHorizontal: 16,
    minWidth: 180,
    maxWidth: 260,
  },
  suggestionText: {
    color: '#222',
    fontSize: 13,
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F2F0E9', // match main background
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderTopWidth: 1,
    borderTopColor: '#DDD',
  },
  input: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 8,
    fontSize: 15,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#DDD',
  },
  sendBtn: {
    padding: 8,
    backgroundColor: '#fff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#DDD',
  },
});

export default AIChat; 